# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
    ]
